//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ZenError {
  ZenError_None = 0,
  ZenError_Unknown = 1,
  ZenError_IsNull = 10,
  ZenError_NotNull = 11,
  ZenError_WrongDataType = 12,
  ZenError_BufferTooSmall = 13,
  ZenError_InvalidArgument = 14,
  ZenError_NotSupported = 15,
  ZenError_AlreadyInitialized = 20,
  ZenError_NotInitialized = 21,
  ZenError_Device_IoTypeInvalid = 30,
  ZenError_Sensor_VersionNotSupported = 31,
  ZenError_Device_ListingFailed = 32,
  ZenError_Device_Listing = 35,
  ZenError_WrongSensorType = 40,
  ZenError_WrongIoType = 41,
  ZenError_UnknownDeviceId = 42,
  ZenError_Io_AlreadyInitialized = 800,
  ZenError_Io_NotInitialized = 801,
  ZenError_Io_InitFailed = 802,
  ZenError_Io_DeinitFailed = 803,
  ZenError_Io_ReadFailed = 804,
  ZenError_Io_SendFailed = 805,
  ZenError_Io_GetFailed = 806,
  ZenError_Io_SetFailed = 807,
  ZenError_Io_Busy = 811,
  ZenError_Io_Timeout = 812,
  ZenError_Io_UnexpectedFunction = 813,
  ZenError_Io_UnsupportedFunction = 814,
  ZenError_Io_MsgCorrupt = 815,
  ZenError_Io_MsgTooBig = 816,
  ZenError_Io_ExpectedAck = 820,
  ZenError_Io_BaudratesUnknown = 821,
  ZenError_UnknownProperty = 850,
  ZenError_UnknownCommandMode = 851,
  ZenError_UnsupportedEvent = 852,
  ZenError_FW_FunctionFailed = 900,
  ZenError_Can_BusError = 1001,
  ZenError_Can_OutOfAddresses = 1002,
  ZenError_Can_ResetFailed = 1006,
  ZenError_Can_AddressOutOfRange = 1009,
  ZenError_InvalidClientHandle = 2000,
  ZenError_InvalidSensorHandle = 2001,
  ZenError_InvalidComponentHandle = 2002,
  ZenError_Max
}
