//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ZenGnssData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ZenGnssData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ZenGnssData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ZenGnssData() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OpenZenPINVOKE.delete_ZenGnssData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int frameCount {
    set {
      OpenZenPINVOKE.ZenGnssData_frameCount_set(swigCPtr, value);
    } 
    get {
      int ret = OpenZenPINVOKE.ZenGnssData_frameCount_get(swigCPtr);
      return ret;
    } 
  }

  public double timestamp {
    set {
      OpenZenPINVOKE.ZenGnssData_timestamp_set(swigCPtr, value);
    } 
    get {
      double ret = OpenZenPINVOKE.ZenGnssData_timestamp_get(swigCPtr);
      return ret;
    } 
  }

  public double latitude {
    set {
      OpenZenPINVOKE.ZenGnssData_latitude_set(swigCPtr, value);
    } 
    get {
      double ret = OpenZenPINVOKE.ZenGnssData_latitude_get(swigCPtr);
      return ret;
    } 
  }

  public double horizontalAccuracy {
    set {
      OpenZenPINVOKE.ZenGnssData_horizontalAccuracy_set(swigCPtr, value);
    } 
    get {
      double ret = OpenZenPINVOKE.ZenGnssData_horizontalAccuracy_get(swigCPtr);
      return ret;
    } 
  }

  public double longitude {
    set {
      OpenZenPINVOKE.ZenGnssData_longitude_set(swigCPtr, value);
    } 
    get {
      double ret = OpenZenPINVOKE.ZenGnssData_longitude_get(swigCPtr);
      return ret;
    } 
  }

  public double verticalAccuracy {
    set {
      OpenZenPINVOKE.ZenGnssData_verticalAccuracy_set(swigCPtr, value);
    } 
    get {
      double ret = OpenZenPINVOKE.ZenGnssData_verticalAccuracy_get(swigCPtr);
      return ret;
    } 
  }

  public double height {
    set {
      OpenZenPINVOKE.ZenGnssData_height_set(swigCPtr, value);
    } 
    get {
      double ret = OpenZenPINVOKE.ZenGnssData_height_get(swigCPtr);
      return ret;
    } 
  }

  public double headingOfMotion {
    set {
      OpenZenPINVOKE.ZenGnssData_headingOfMotion_set(swigCPtr, value);
    } 
    get {
      double ret = OpenZenPINVOKE.ZenGnssData_headingOfMotion_get(swigCPtr);
      return ret;
    } 
  }

  public double headingOfVehicle {
    set {
      OpenZenPINVOKE.ZenGnssData_headingOfVehicle_set(swigCPtr, value);
    } 
    get {
      double ret = OpenZenPINVOKE.ZenGnssData_headingOfVehicle_get(swigCPtr);
      return ret;
    } 
  }

  public double headingAccuracy {
    set {
      OpenZenPINVOKE.ZenGnssData_headingAccuracy_set(swigCPtr, value);
    } 
    get {
      double ret = OpenZenPINVOKE.ZenGnssData_headingAccuracy_get(swigCPtr);
      return ret;
    } 
  }

  public double velocity {
    set {
      OpenZenPINVOKE.ZenGnssData_velocity_set(swigCPtr, value);
    } 
    get {
      double ret = OpenZenPINVOKE.ZenGnssData_velocity_get(swigCPtr);
      return ret;
    } 
  }

  public double velocityAccuracy {
    set {
      OpenZenPINVOKE.ZenGnssData_velocityAccuracy_set(swigCPtr, value);
    } 
    get {
      double ret = OpenZenPINVOKE.ZenGnssData_velocityAccuracy_get(swigCPtr);
      return ret;
    } 
  }

  public ZenGnssFixType fixType {
    set {
      OpenZenPINVOKE.ZenGnssData_fixType_set(swigCPtr, (int)value);
    } 
    get {
      ZenGnssFixType ret = (ZenGnssFixType)OpenZenPINVOKE.ZenGnssData_fixType_get(swigCPtr);
      return ret;
    } 
  }

  public ZenGnssFixCarrierPhaseSolution carrierPhaseSolution {
    set {
      OpenZenPINVOKE.ZenGnssData_carrierPhaseSolution_set(swigCPtr, (int)value);
    } 
    get {
      ZenGnssFixCarrierPhaseSolution ret = (ZenGnssFixCarrierPhaseSolution)OpenZenPINVOKE.ZenGnssData_carrierPhaseSolution_get(swigCPtr);
      return ret;
    } 
  }

  public byte numberSatellitesUsed {
    set {
      OpenZenPINVOKE.ZenGnssData_numberSatellitesUsed_set(swigCPtr, value);
    } 
    get {
      byte ret = OpenZenPINVOKE.ZenGnssData_numberSatellitesUsed_get(swigCPtr);
      return ret;
    } 
  }

  public ushort year {
    set {
      OpenZenPINVOKE.ZenGnssData_year_set(swigCPtr, value);
    } 
    get {
      ushort ret = OpenZenPINVOKE.ZenGnssData_year_get(swigCPtr);
      return ret;
    } 
  }

  public byte month {
    set {
      OpenZenPINVOKE.ZenGnssData_month_set(swigCPtr, value);
    } 
    get {
      byte ret = OpenZenPINVOKE.ZenGnssData_month_get(swigCPtr);
      return ret;
    } 
  }

  public byte day {
    set {
      OpenZenPINVOKE.ZenGnssData_day_set(swigCPtr, value);
    } 
    get {
      byte ret = OpenZenPINVOKE.ZenGnssData_day_get(swigCPtr);
      return ret;
    } 
  }

  public byte hour {
    set {
      OpenZenPINVOKE.ZenGnssData_hour_set(swigCPtr, value);
    } 
    get {
      byte ret = OpenZenPINVOKE.ZenGnssData_hour_get(swigCPtr);
      return ret;
    } 
  }

  public byte minute {
    set {
      OpenZenPINVOKE.ZenGnssData_minute_set(swigCPtr, value);
    } 
    get {
      byte ret = OpenZenPINVOKE.ZenGnssData_minute_get(swigCPtr);
      return ret;
    } 
  }

  public byte second {
    set {
      OpenZenPINVOKE.ZenGnssData_second_set(swigCPtr, value);
    } 
    get {
      byte ret = OpenZenPINVOKE.ZenGnssData_second_get(swigCPtr);
      return ret;
    } 
  }

  public int nanoSecondCorrection {
    set {
      OpenZenPINVOKE.ZenGnssData_nanoSecondCorrection_set(swigCPtr, value);
    } 
    get {
      int ret = OpenZenPINVOKE.ZenGnssData_nanoSecondCorrection_get(swigCPtr);
      return ret;
    } 
  }

  public ZenGnssData() : this(OpenZenPINVOKE.new_ZenGnssData(), true) {
  }

}
