//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum EZenSensorProperty {
  ZenSensorProperty_Invalid = 0,
  ZenSensorProperty_DeviceName = 1000,
  ZenSensorProperty_FirmwareInfo,
  ZenSensorProperty_FirmwareVersion,
  ZenSensorProperty_SerialNumber,
  ZenSensorProperty_RestoreFactorySettings,
  ZenSensorProperty_StoreSettingsInFlash,
  ZenSensorProperty_BatteryCharging,
  ZenSensorProperty_BatteryLevel,
  ZenSensorProperty_BatteryVoltage,
  ZenSensorProperty_BaudRate,
  ZenSensorProperty_SupportedBaudRates,
  ZenSensorProperty_DataMode,
  ZenSensorProperty_TimeOffset,
  ZenSensorProperty_SensorModel,
  ZenSensorProperty_SensorSpecific_Start = 10000,
  ZenSensorProperty_SensorSpecific_End = 19999,
  ZenSensorProperty_Max
}
