//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ZenEventType {
  ZenEventType_None = 0,
  ZenEventType_SensorFound = 1,
  ZenEventType_SensorListingProgress = 2,
  ZenEventType_SensorDisconnected = 3,
  ZenEventType_ImuData = 100,
  ZenEventType_GnssData = 200,
  ZenEventType_SensorSpecific_Start = 1000,
  ZenEventType_SensorSpecific_End = 1999,
  ZenEventType_ImuComponentSpecific_Start = 2000,
  ZenEventType_ImuComponentSpecific_End = 2999,
  ZenEventType_GnssComponentSpecific_Start = 3000,
  ZenEventType_GnssComponentSpecific_End = 3999,
  ZenEventType_Max
}
