//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ZenGnssFixType {
  ZenGnssFixType_NoFix = 0,
  ZenGnssFixType_DeadReckoningOnly = 1,
  ZenGnssFixType_2dFix = 2,
  ZenGnssFixType_3dFix = 3,
  ZenGnssFixType_GnssAndDeadReckoning = 4,
  ZenGnssFixType_TimeOnlyFix = 5,
  ZenGnssFixType_Max
}
