//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ZenLogLevel {
  ZenLogLevel_Off,
  ZenLogLevel_Error,
  ZenLogLevel_Warning,
  ZenLogLevel_Info,
  ZenLogLevel_Debug,
  ZenLogLevel_Max
}
