//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ZenOrientationOffsetMode {
  ZenOrientationOffsetMode_Object = 0,
  ZenOrientationOffsetMode_Heading = 1,
  ZenOrientationOffsetMode_Alignment = 2,
  ZenOrientationOffsetMode_Max
}
