//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ZenPropertyType {
  ZenPropertyType_Invalid = 0,
  ZenPropertyType_Byte = 1,
  ZenPropertyType_Bool = 2,
  ZenPropertyType_Float = 3,
  ZenPropertyType_Int32 = 4,
  ZenPropertyType_UInt64 = 5,
  ZenPropertyType_Max
}
