//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VRIF : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single LeftGrip
        {
            get
            {
                return SteamVR_Actions.vRIF_LeftGrip;
            }
        }
        
        public virtual SteamVR_Action_Single RightGrip
        {
            get
            {
                return SteamVR_Actions.vRIF_RightGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean AButton
        {
            get
            {
                return SteamVR_Actions.vRIF_AButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean BButton
        {
            get
            {
                return SteamVR_Actions.vRIF_BButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean XButton
        {
            get
            {
                return SteamVR_Actions.vRIF_XButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean YButton
        {
            get
            {
                return SteamVR_Actions.vRIF_YButton;
            }
        }
        
        public virtual SteamVR_Action_Single LeftTrigger
        {
            get
            {
                return SteamVR_Actions.vRIF_LeftTrigger;
            }
        }
        
        public virtual SteamVR_Action_Single RightTrigger
        {
            get
            {
                return SteamVR_Actions.vRIF_RightTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftTriggerNear
        {
            get
            {
                return SteamVR_Actions.vRIF_LeftTriggerNear;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTriggerNear
        {
            get
            {
                return SteamVR_Actions.vRIF_RightTriggerNear;
            }
        }
        
        public virtual SteamVR_Action_Vector2 LeftThumbstickAxis
        {
            get
            {
                return SteamVR_Actions.vRIF_LeftThumbstickAxis;
            }
        }
        
        public virtual SteamVR_Action_Vector2 RightThumbstickAxis
        {
            get
            {
                return SteamVR_Actions.vRIF_RightThumbstickAxis;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftThumbstickNear
        {
            get
            {
                return SteamVR_Actions.vRIF_LeftThumbstickNear;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightThumbstickNear
        {
            get
            {
                return SteamVR_Actions.vRIF_RightThumbstickNear;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftThumbstickDown
        {
            get
            {
                return SteamVR_Actions.vRIF_LeftThumbstickDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightThumbstickDown
        {
            get
            {
                return SteamVR_Actions.vRIF_RightThumbstickDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean Start
        {
            get
            {
                return SteamVR_Actions.vRIF_Start;
            }
        }
        
        public virtual SteamVR_Action_Boolean Back
        {
            get
            {
                return SteamVR_Actions.vRIF_Back;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.vRIF_Haptic;
            }
        }
    }
}
