//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum EZenGnssProperty {
  ZenGnssProperty_Invalid = 0,
  ZenGnssProperty_OutputNavPvtiTOW,
  ZenGnssProperty_OutputNavPvtYear,
  ZenGnssProperty_OutputNavPvtMonth,
  ZenGnssProperty_OutputNavPvtDay,
  ZenGnssProperty_OutputNavPvtHour,
  ZenGnssProperty_OutputNavPvtMinute,
  ZenGnssProperty_OutputNavPvtSecond,
  ZenGnssProperty_OutputNavPvtValid,
  ZenGnssProperty_OutputNavPvttAcc,
  ZenGnssProperty_OutputNavPvtNano,
  ZenGnssProperty_OutputNavPvtFixType,
  ZenGnssProperty_OutputNavPvtFlags,
  ZenGnssProperty_OutputNavPvtFlags2,
  ZenGnssProperty_OutputNavPvtNumSV,
  ZenGnssProperty_OutputNavPvtLongitude,
  ZenGnssProperty_OutputNavPvtLatitude,
  ZenGnssProperty_OutputNavPvtHeight,
  ZenGnssProperty_OutputNavPvthMSL,
  ZenGnssProperty_OutputNavPvthAcc,
  ZenGnssProperty_OutputNavPvtvAcc,
  ZenGnssProperty_OutputNavPvtVelN,
  ZenGnssProperty_OutputNavPvtVelE,
  ZenGnssProperty_OutputNavPvtVelD,
  ZenGnssProperty_OutputNavPvtgSpeed,
  ZenGnssProperty_OutputNavPvtHeadMot,
  ZenGnssProperty_OutputNavPvtsAcc,
  ZenGnssProperty_OutputNavPvtHeadAcc,
  ZenGnssProperty_OutputNavPvtpDOP,
  ZenGnssProperty_OutputNavPvtHeadVeh,
  ZenGnssProperty_OutputNavAttiTOW,
  ZenGnssProperty_OutputNavAttVersion,
  ZenGnssProperty_OutputNavAttRoll,
  ZenGnssProperty_OutputNavAttPitch,
  ZenGnssProperty_OutputNavAttHeading,
  ZenGnssProperty_OutputNavAttAccRoll,
  ZenGnssProperty_OutputNavAttAccPitch,
  ZenGnssProperty_OutputNavAttAccHeading,
  ZenGnssProperty_OutputEsfStatusiTOW,
  ZenGnssProperty_OutputEsfStatusVersion,
  ZenGnssProperty_OutputEsfStatusInitStatus1,
  ZenGnssProperty_OutputEsfStatusInitStatus2,
  ZenGnssProperty_OutputEsfStatusFusionMode,
  ZenGnssProperty_OutputEsfStatusNumSens,
  ZenGnssProperty_OutputEsfStatusSensStatus,
  ZenGnssProperty_Max
}
