//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;

public class OpenZenFloatArray : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OpenZenFloatArray(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OpenZenFloatArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~OpenZenFloatArray() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OpenZenPINVOKE.delete_OpenZenFloatArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public OpenZenFloatArray(int nelements) : this(OpenZenPINVOKE.new_OpenZenFloatArray(nelements), true) {
  }

  public float getitem(int index) {
    float ret = OpenZenPINVOKE.OpenZenFloatArray_getitem(swigCPtr, index);
    return ret;
  }

  public void setitem(int index, float value) {
    OpenZenPINVOKE.OpenZenFloatArray_setitem(swigCPtr, index, value);
  }

  public SWIGTYPE_p_float cast() {
    global::System.IntPtr cPtr = OpenZenPINVOKE.OpenZenFloatArray_cast(swigCPtr);
    SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
    return ret;
  }

  public static OpenZenFloatArray frompointer(SWIGTYPE_p_float t) {
    global::System.IntPtr cPtr = OpenZenPINVOKE.OpenZenFloatArray_frompointer(SWIGTYPE_p_float.getCPtr(t));
    OpenZenFloatArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new OpenZenFloatArray(cPtr, false);
    return ret;
  }

    public static double frompointer(double timestamp)
    {
        throw new NotImplementedException();
    }
}
