//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ZenSensorInitError {
  ZenSensorInitError_None = 0,
  ZenSensorInitError_InvalidHandle,
  ZenSensorInitError_IsNull,
  ZenSensorInitError_UnknownIdentifier,
  ZenSensorInitError_UnsupportedComponent,
  ZenSensorInitError_UnsupportedDataFormat,
  ZenSensorInitError_UnsupportedIoType,
  ZenSensorInitError_UnsupportedProtocol,
  ZenSensorInitError_UnsupportedFunction,
  ZenSensorInitError_ConnectFailed,
  ZenSensorInitError_IoFailed,
  ZenSensorInitError_RetrieveFailed,
  ZenSensorInitError_SetBaudRateFailed,
  ZenSensorInitError_SendFailed,
  ZenSensorInitError_Timeout,
  ZenSensorInitError_IncompatibleBaudRates,
  ZenSensorInitError_InvalidAddress,
  ZenSensorInitError_InvalidConfig,
  ZenSensorInitError_NoConfiguration,
  ZenSensorInitError_Max
}
